import Image from 'next/image'

export default function Home() {
  return (
    <main>
      <h1>Adventura</h1>
      <h2>冒険を始めよう</h2>
      <div>
        <Image
          src="/images/male-characters/m-yusha.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/male-characters/m-monk.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/male-characters/m-thief.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/male-characters/m-traveler.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/male-characters/m-wizard.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/male-characters/m-warrior.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
      </div>
      <div>
        <Image
          src="/images/female-characters/f-yusha.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/female-characters/f-monk.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/female-characters/f-thief.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/female-characters/f-traveler.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/female-characters/f-wizard.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
        <Image
          src="/images/female-characters/f-warrior.png"
          alt="yusha"
          width={200}
          height={200}
        ></Image>
      </div>
    </main>
  )
}
